; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=instcombine < %s | FileCheck %s

declare void @use.i1(i1 %x)
declare void @use.i64(i64 %x)
declare void @use.i64i1({i64, i1} %x)

define i1 @umul_less_than_and_no_overflow_const(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i64 [[IN]], 6
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 168)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  ret i1 %ret
}

define i1 @umul_less_than_and_no_overflow_const_i8(i8 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_i8(
; CHECK-SAME: i8 [[IN:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i8 [[IN]], 5
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i8, i1 } @llvm.umul.with.overflow.i8(i8 %in, i8 24)
  %mul = extractvalue { i8, i1 } %mwo, 0
  %ovf = extractvalue { i8, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i8 %mul, 100
  %ret = and i1 %novf, %cmp
  ret i1 %ret
}

define i1 @umul_less_than_and_no_overflow_const_commuted(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_commuted(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i64 [[IN]], 6
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 168)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %cmp, %novf
  ret i1 %ret
}

define i1 @umul_less_than_and_no_overflow_const_exact_multiple(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_exact_multiple(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i64 [[IN]], 10
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 480
  %ret = and i1 %novf, %cmp
  ret i1 %ret
}

; TODO: icmp ult %mul, 1 is canonicalized to icmp eq %mul, 0 first, which is
; not handled.
define i1 @umul_less_than_and_no_overflow_const_one(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_one(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 [[IN]], i64 48)
; CHECK-NEXT:    [[MUL:%.*]] = extractvalue { i64, i1 } [[MWO]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { i64, i1 } [[MWO]], 1
; CHECK-NEXT:    [[NOVF:%.*]] = xor i1 [[OVF]], true
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[MUL]], 0
; CHECK-NEXT:    [[RET:%.*]] = and i1 [[CMP]], [[NOVF]]
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1
  %ret = and i1 %novf, %cmp
  ret i1 %ret
}

define i1 @umul_less_than_and_no_overflow_const_max_multiplier(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_max_multiplier(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp eq i64 [[IN]], 0
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 -1)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, -16
  %ret = and i1 %novf, %cmp
  ret i1 %ret
}

define i1 @umul_less_than_and_no_overflow_const_multiuse_mul(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_multiuse_mul(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[MUL:%.*]] = mul i64 [[IN]], 48
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i64 [[IN]], 21
; CHECK-NEXT:    call void @use.i64(i64 [[MUL]])
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  call void @use.i64(i64 %mul)
  ret i1 %ret
}

define i1 @umul_less_than_and_no_overflow_const_multiuse_overflow(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_multiuse_overflow(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[OVF:%.*]] = icmp ugt i64 [[IN]], 384307168202282325
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i64 [[IN]], 21
; CHECK-NEXT:    call void @use.i1(i1 [[OVF]])
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  call void @use.i1(i1 %ovf)
  ret i1 %ret
}

define i1 @umul_less_than_and_no_overflow_const_multiuse_not(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_multiuse_not(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[NOVF:%.*]] = icmp ult i64 [[IN]], 384307168202282326
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i64 [[IN]], 21
; CHECK-NEXT:    call void @use.i1(i1 [[NOVF]])
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  call void @use.i1(i1 %novf)
  ret i1 %ret
}

define i1 @umul_less_than_and_no_overflow_const_multiuse_umul_call(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_multiuse_umul_call(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 [[IN]], i64 48)
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i64 [[IN]], 21
; CHECK-NEXT:    call void @use.i64i1({ i64, i1 } [[MWO]])
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  call void @use.i64i1({ i64, i1 } %mwo)
  ret i1 %ret
}

define <2 x i1> @umul_less_than_and_no_overflow_const_vector_splat(<2 x i64> %in) {
; CHECK-LABEL: define <2 x i1> @umul_less_than_and_no_overflow_const_vector_splat(
; CHECK-SAME: <2 x i64> [[IN:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp ult <2 x i64> [[IN]], splat (i64 6)
; CHECK-NEXT:    ret <2 x i1> [[RET]]
;
  %mwo = call { <2 x i64>, <2 x i1> } @llvm.umul.with.overflow.v2i64(<2 x i64> %in, <2 x i64> splat (i64 168))
  %mul = extractvalue { <2 x i64>, <2 x i1> } %mwo, 0
  %ovf = extractvalue { <2 x i64>, <2 x i1> } %mwo, 1
  %novf = xor <2 x i1> %ovf, splat (i1 true)
  %cmp = icmp ult <2 x i64> %mul, splat (i64 1000)
  %ret = and <2 x i1> %novf, %cmp
  ret <2 x i1> %ret
}

define i1 @umul_less_than_logical_and_no_overflow_const(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_logical_and_no_overflow_const(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i64 [[IN]], 6
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 168)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = select i1 %novf, i1 %cmp, i1 false
  ret i1 %ret
}

; Reduced from the Linux kernel (dmar_free_unused_resources).
define i1 @umul_less_than_and_no_overflow_const_sext(i32 %x) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_sext(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i32 [[X]], 14
; CHECK-NEXT:    ret i1 [[RET]]
;
  %e = sext i32 %x to i64
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %e, i64 3)
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %mul = extractvalue { i64, i1 } %mwo, 0
  %cmp = icmp ult i64 %mul, 41
  %novf = xor i1 %ovf, true
  %ret = and i1 %cmp, %novf
  ret i1 %ret
}

; Negative test
define <2 x i1> @umul_less_than_and_no_overflow_const_vector_non_splat_negative(<2 x i64> %in) {
; CHECK-LABEL: define <2 x i1> @umul_less_than_and_no_overflow_const_vector_non_splat_negative(
; CHECK-SAME: <2 x i64> [[IN:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { <2 x i64>, <2 x i1> } @llvm.umul.with.overflow.v2i64(<2 x i64> [[IN]], <2 x i64> <i64 24, i64 168>)
; CHECK-NEXT:    [[MUL:%.*]] = extractvalue { <2 x i64>, <2 x i1> } [[MWO]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { <2 x i64>, <2 x i1> } [[MWO]], 1
; CHECK-NEXT:    [[NOVF:%.*]] = xor <2 x i1> [[OVF]], splat (i1 true)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult <2 x i64> [[MUL]], <i64 100, i64 1000>
; CHECK-NEXT:    [[RET:%.*]] = and <2 x i1> [[CMP]], [[NOVF]]
; CHECK-NEXT:    ret <2 x i1> [[RET]]
;
  %mwo = call { <2 x i64>, <2 x i1> } @llvm.umul.with.overflow.v2i64(<2 x i64> %in, <2 x i64> <i64 24, i64 168>)
  %mul = extractvalue { <2 x i64>, <2 x i1> } %mwo, 0
  %ovf = extractvalue { <2 x i64>, <2 x i1> } %mwo, 1
  %novf = xor <2 x i1> %ovf, splat (i1 true)
  %cmp = icmp ult <2 x i64> %mul, <i64 100, i64 1000>
  %ret = and <2 x i1> %novf, %cmp
  ret <2 x i1> %ret
}

; Negative test
define <2 x i1> @umul_less_than_and_no_overflow_const_vector_poison_non_splat_negative(<2 x i64> %in) {
; CHECK-LABEL: define <2 x i1> @umul_less_than_and_no_overflow_const_vector_poison_non_splat_negative(
; CHECK-SAME: <2 x i64> [[IN:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { <2 x i64>, <2 x i1> } @llvm.umul.with.overflow.v2i64(<2 x i64> [[IN]], <2 x i64> <i64 poison, i64 168>)
; CHECK-NEXT:    [[MUL:%.*]] = extractvalue { <2 x i64>, <2 x i1> } [[MWO]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { <2 x i64>, <2 x i1> } [[MWO]], 1
; CHECK-NEXT:    [[NOVF:%.*]] = xor <2 x i1> [[OVF]], splat (i1 true)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult <2 x i64> [[MUL]], <i64 1000, i64 poison>
; CHECK-NEXT:    [[RET:%.*]] = and <2 x i1> [[CMP]], [[NOVF]]
; CHECK-NEXT:    ret <2 x i1> [[RET]]
;
  %mwo = call { <2 x i64>, <2 x i1> } @llvm.umul.with.overflow.v2i64(<2 x i64> %in, <2 x i64> <i64 poison, i64 168>)
  %mul = extractvalue { <2 x i64>, <2 x i1> } %mwo, 0
  %ovf = extractvalue { <2 x i64>, <2 x i1> } %mwo, 1
  %novf = xor <2 x i1> %ovf, splat (i1 true)
  %cmp = icmp ult <2 x i64> %mul, <i64 1000, i64 poison>
  %ret = and <2 x i1> %novf, %cmp
  ret <2 x i1> %ret
}

; Negative test
define i1 @umul_less_than_and_overflow_const_negative(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_overflow_const_negative(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 [[IN]], i64 48)
; CHECK-NEXT:    [[MUL:%.*]] = extractvalue { i64, i1 } [[MWO]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { i64, i1 } [[MWO]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[MUL]], 1000
; CHECK-NEXT:    [[RET:%.*]] = and i1 [[OVF]], [[CMP]]
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %ovf, %cmp
  ret i1 %ret
}

; Negative test
define i1 @umul_less_than_or_no_overflow_const_negative(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_or_no_overflow_const_negative(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 [[IN]], i64 48)
; CHECK-NEXT:    [[MUL:%.*]] = extractvalue { i64, i1 } [[MWO]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { i64, i1 } [[MWO]], 1
; CHECK-NEXT:    [[NOVF:%.*]] = xor i1 [[OVF]], true
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[MUL]], 1000
; CHECK-NEXT:    [[RET:%.*]] = or i1 [[CMP]], [[NOVF]]
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = or i1 %novf, %cmp
  ret i1 %ret
}

; Negative test
define i1 @umul_greater_than_and_no_overflow_const_negative(i64 %in) {
; CHECK-LABEL: define i1 @umul_greater_than_and_no_overflow_const_negative(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 [[IN]], i64 48)
; CHECK-NEXT:    [[MUL:%.*]] = extractvalue { i64, i1 } [[MWO]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { i64, i1 } [[MWO]], 1
; CHECK-NEXT:    [[NOVF:%.*]] = xor i1 [[OVF]], true
; CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i64 [[MUL]], 1000
; CHECK-NEXT:    [[RET:%.*]] = and i1 [[CMP]], [[NOVF]]
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ugt i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  ret i1 %ret
}

; Negative test
define i1 @umul_less_than_and_no_overflow_const_multiuse_icmp_negative(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_multiuse_icmp_negative(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 [[IN]], i64 48)
; CHECK-NEXT:    [[MUL:%.*]] = extractvalue { i64, i1 } [[MWO]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { i64, i1 } [[MWO]], 1
; CHECK-NEXT:    [[NOVF:%.*]] = xor i1 [[OVF]], true
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[MUL]], 1000
; CHECK-NEXT:    [[RET:%.*]] = and i1 [[CMP]], [[NOVF]]
; CHECK-NEXT:    call void @use.i1(i1 [[CMP]])
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 48)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  call void @use.i1(i1 %cmp)
  ret i1 %ret
}

; Negative test
define i1 @umul_less_than_and_no_overflow_var_negative(i64 %in, i64 %c) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_var_negative(
; CHECK-SAME: i64 [[IN:%.*]], i64 [[C:%.*]]) {
; CHECK-NEXT:    [[MWO:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 [[IN]], i64 [[C]])
; CHECK-NEXT:    [[MUL:%.*]] = extractvalue { i64, i1 } [[MWO]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { i64, i1 } [[MWO]], 1
; CHECK-NEXT:    [[NOVF:%.*]] = xor i1 [[OVF]], true
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[MUL]], 1000
; CHECK-NEXT:    [[RET:%.*]] = and i1 [[CMP]], [[NOVF]]
; CHECK-NEXT:    ret i1 [[RET]]
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 %c)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  ret i1 %ret
}

; Negative test. The umul.with.overflow should be folded away before.
define i1 @umul_less_than_and_no_overflow_const_0_negative(i64 %in) {
; CHECK-LABEL: define i1 @umul_less_than_and_no_overflow_const_0_negative(
; CHECK-SAME: i64 [[IN:%.*]]) {
; CHECK-NEXT:    ret i1 true
;
  %mwo = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 %in, i64 0)
  %mul = extractvalue { i64, i1 } %mwo, 0
  %ovf = extractvalue { i64, i1 } %mwo, 1
  %novf = xor i1 %ovf, true
  %cmp = icmp ult i64 %mul, 1000
  %ret = and i1 %novf, %cmp
  ret i1 %ret
}
